### ISSUE TITLE
Can't get authentication token (FIXED)

### ISSUE THREAD

**Issue by BasvdW22** [wvanbreukelen/ZermeloRoosterPHP#10]
I'll just post some code and what it returns for me:
```php
<?php
require('custom_autoload.php');

register_api();

$zermelo = new ZermeloAPI('candea');
```
returns:
```
PHP Fatal error:  Call to undefined function register_api() in /home/pi/ZermeloRoosterPHP/rooster.php on line 4
```
(Has to be "register_zermelo_api()" maybe?
returns:
```
PHP Fatal error:  Uncaught exception 'Exception' with message 'Cache.php has not been found!' in /home/pi/ZermeloRoosterPHP/custom_autoload.php:9
Stack trace:
#0 /home/pi/ZermeloRoosterPHP/rooster.php(4): register_zermelo_api()
#1 {main}
  thrown in /home/pi/ZermeloRoosterPHP/custom_autoload.php on line 9
```
)

```php
<?php
require('Zermelo.php');
require('Cache.php');

$zermelo = new ZermeloAPI('candea');
$zermelo->grabAccessToken('114728', '600930934346');
```
returns:
```
PHP Warning:  The use statement with non-compound name 'Exception' has no effect in /home/pi/ZermeloRoosterPHP/Zermelo.php on line 4
PHP Fatal error:  Call to protected method ZermeloAPI\Cache::saveToken() from context 'ZermeloAPI' in /home/pi/ZermeloRoosterPHP/Zermelo.php on line 220
```
the first time and:
```
PHP Warning:  The use statement with non-compound name 'Exception' has no effect in /home/pi/ZermeloRoosterPHP/Zermelo.php on line 4
PHP Fatal error:  Uncaught exception 'Exception' with message 'Cannot grab access token, did you double checked the code from the portal?' in /home/pi/ZermeloRoosterPHP/Zermelo.php:212
Stack trace:
#0 /home/pi/ZermeloRoosterPHP/rooster.php(6): ZermeloAPI->grabAccessToken('114728', '600930934346')
#1 {main}
  thrown in /home/pi/ZermeloRoosterPHP/Zermelo.php on line 212
```
the second time.
I don't really know PHP that well, am I doing something wrong here (or should I first focus on learning PHP)?
It seems so easy but I can't get it to work.

**Comment by wvanbreukelen** [comment]
Yeah, the function you want to call is indeed register_zermelo_api(). I forgot to edit that in the readme itself ;P. 

For the cache.php exception, can you double check if a Cache.php file actually exists in the project root directory (i think this is the /home/pi/ZermeloRoosterPHP/   directory)?
Or just send me a screenshot with the file structure.

Also, you can change

```php
<?php
require('Zermelo.php');
require('Cache.php');

$zermelo = new ZermeloAPI('candea');
$zermelo->grabAccessToken('114728', '600930934346');
```

Into this

```php
<?php

require('custom_autoload.php');

$zermelo = new ZermeloAPI('candea');
$zermelo->grabAccessToken('114728', '600930934346');
```

The custom autoload will automatically load in all the files that are required.

**Comment by BasvdW22** [comment]
Ah okay, thanks. Also, in custom_autoload.php it checks for cache.json instead of cache.php, is it supposed to be like that? (I'm at school now so can't test it myself.)

**Comment by wvanbreukelen** [comment]
That weird, I see that. I pushed out a new commit, so the issue with the cache.php file has been resolved I suppose.
I cannot test it right now (also in school ;(.

Please test again and send the results back to this issue, please :)

**Comment by wvanbreukelen** [comment]
Is everything working properly?

**Comment by BasvdW22** [comment]
Getting
```
PHP Fatal error:  Call to protected method ZermeloAPI\Cache::saveToken() from context 'ZermeloAPI' in /home/pi/ZermeloRoosterPHP/Zermelo.php on line 219
```
on the first try and
```
PHP Fatal error:  Uncaught exception 'Exception' with message 'Cannot grab access token, did you double checked the code from the portal?' in /home/pi/ZermeloRoosterPHP/Zermelo.php:211
Stack trace:
#0 /home/pi/ZermeloRoosterPHP/rooster.php(8): ZermeloAPI->grabAccessToken('114728', '409258364908')
#1 {main}
  thrown in /home/pi/ZermeloRoosterPHP/Zermelo.php on line 211
```
On the second with
```php
<?php

require('custom_autoload.php');

register_zermelo_api();

$zermelo = new ZermeloAPI('candea');
$zermelo->grabAccessToken('114728', '409258364908');
```

**Comment by wvanbreukelen** [comment]
I am updating the code, please do a git pull to get the latest changes. Also, please make sure that you use a new code out of the zermelo portal (so not 409258364908, try a new one).

Grabbing the access token is working perfectly fine for me at the moment.
I have some issues with getting the grid information

**Comment by wvanbreukelen** [comment]
Any progress?

**Comment by BasvdW22** [comment]
I'm sorry, I went to guitar lesson.

Now I get
```
PHP Warning:  file_get_contents(): Filename cannot be empty in /home/pi/V3A-WhatsApp-Bot/ZermeloRoosterPHP/Cache.php on line 34
PHP Warning:  file_put_contents(): Filename cannot be empty in /home/pi/V3A-WhatsApp-Bot/ZermeloRoosterPHP/Cache.php on line 38
```
And yes, I use a new code every time.

**Comment by wvanbreukelen** [comment]
No problem, I've just pushed out a new commit. Can you post the results back to the issue, please?

**Comment by BasvdW22** [comment]
The code I use is different on every new try.
```
PHP Fatal error:  Uncaught exception 'Exception' with message 'File location is not set! File location: ' in /home/pi/V3A-WhatsApp-Bot/ZermeloRoosterPHP/Zermelo.php:395
Stack trace:
#0 /home/pi/V3A-WhatsApp-Bot/ZermeloRoosterPHP/Zermelo.php(41): ZermeloAPI->setCache(NULL)
#1 /home/pi/V3A-WhatsApp-Bot/ZermeloRoosterPHP/rooster.php(7): ZermeloAPI->__construct('candea')
#2 {main}
  thrown in /home/pi/V3A-WhatsApp-Bot/ZermeloRoosterPHP/Zermelo.php on line 395
```
Soo.. how do I set the file location? (As it appears to be empty I guess.)

**Comment by wvanbreukelen** [comment]
Ok, I have figured out the problem.

When the cache location is added, the code was checking if the cache.json file does actually exists.
But the cache.json file does not exists, and so the cache location cannot been set.

Please create a new cache.json in the folder /home/pi/ZermeloRoosterPHP/
So the final path of the file will look like /home/pi/ZermeloRoosterPHP/cache.json

In the cache.json file, please put the following content:

```json
{

}
```

Please report the results, thanks :+1:

**Comment by BasvdW22** [comment]
Woohoo, that worked! Thank you very much! :smile: 
(Content of cache.json is now
```json
{"tokens":{"114728":"jlons1qmcie1736tecplqvj6o0"}}
```

**Comment by wvanbreukelen** [comment]
Yeah, that seems to be OK!

Now try to run

```php
print_r($this->getStudentGrid('114728'));
```

Please report back (maybe a part of) the results

**Comment by BasvdW22** [comment]
Uhh...
```
PHP Fatal error:  Using $this when not in object context in /home/pi/V3A-WhatsApp-Bot/ZermeloRoosterPHP/rooster.php on line 4
```

**Comment by wvanbreukelen** [comment]
Oh shit lol, my fault

print_r($zermelo->getStudentGrid('114728'));

**Comment by BasvdW22** [comment]
Yea, I figured that out the same time as you responded :P.
So, my final code is:
```php
<?php
require('custom_autoload.php');

register_zermelo_api();
$zermelo = new ZermeloAPI('candea');

print_r($zermelo->getStudentGrid('114728'));
```
which returns:
```
Array
(
)
```

**Comment by wvanbreukelen** [comment]
Yeah, you got the same issue as me. I am going to fix in the next hour or so, otherwise expect to be fixed tomorrow.

**Comment by BasvdW22** [comment]
Alright, take your time! :P

**Comment by wvanbreukelen** [comment]
Ok, that was a quick fix LOL

Please report back (maybe a part of) the results.

**Comment by BasvdW22** [comment]
Wow, very fast indeed.
And it works now!
One of the lessons:
```
[40] => Array
        (
            [id] => 81069
            [start] => 1442580300
            [end] => 1442583000
            [subjects] => Array
                (
                    [0] => ne
                )

            [teachers] => Array
                (
                    [0] => st
                )

            [groups] => Array
                (
                    [0] => v3a
                )

            [locations] => Array
                (
                    [0] => s002
                )

            [type] => lesson
            [remark] => 
            [valid] => 1
            [cancelled] => 
            [modified] => 
            [moved] => 
            [changeDescription] => 
            [startTimeSlot] => 9
            [endTimeSlot] => 9
            [branch] => candea
            [branchOfSchool] => 
            [created] => 1441784211
            [lastModified] => 1441784211
            [hidden] => 
            [appointmentInstance] => 9813
            [new] => 
            [start_date] => 18/09/2015 14:45
            [end_date] => 18/09/2015 15:30
            [hour] => 6
        )
```
Thank you very much (again)! :smile: 

P.S. Everytime you mentioned me somewhere you mentioned @basvdW instead of @BasvdW (and @basvdW is an other person) :P

**Comment by wvanbreukelen** [comment]
Haha, lololol

How long are your lessons 45 minutes, or 60 minutes?
Maybe the last parameter [hour] is not working properly, because it has been programmed for 60 minutes lessons.

Maybe I can fix this issue later on.

If you have any other questions (other (programming) languages), I am here to help :)

PS lol we actually both speak dutch I think, but I respond in english because it is the easiest for explaining programming shizzle. ;)

**Comment by BasvdW22** [comment]
Yea, my lessons are 45 minutes, I also saw that the "hour" thing was wrong.
And yep, I'm Dutch too, and I already knew you are also Dutch because of your last name, the fact that you're working/worked together with someone called JulianvDoorn on a "GriftlandRoosters" app :P.
My full name is "Bas van den Wollenberg", and on my profile page you can see I'm from Arnhem.
I also thought English would be better use for communication.
I'm happy you can help me with this and other stuff, as I'm still fairly new into programming :smile:.
Thank you again!

**Comment by wvanbreukelen** [comment]
Yeah, that's right, that is a friend of mine but the development for the app stopped at the moment because he "heeft geen zin" 

Thanks, that is great to hear. My name is actually "Wiebe" and I live in Soest, Utrecht.

**Comment by BasvdW22** [comment]
Just noticed that everything is correct ("startTimeslot" and "endTimeslot" is the number of the lesson we have that day, I thought "hour" had to represent that), but what is "hour" then?

**Comment by wvanbreukelen** [comment]
"hour" is a calculation that is made by the ZermeloRoosterAPI class, so it is not data from the portal itself.

**Comment by BasvdW22** [comment]
Sooo it's not that important?

**Comment by wvanbreukelen** [comment]
For you, not really. For me, yes it is important. My school don't supply the startTimeslot and endTimeslot parameters I think.

**Comment by BasvdW22** [comment]
Ahh okay, thanks. 
And I just saw you asked what I'm building, currently working on a WhatsApp bot for my class that sends timetables on request and stuff. It's pretty interesting in my opinion. Although I don't really know PHP, but I'm learning on the go :P.

**Comment by wvanbreukelen** [comment]
Oh ok, I  have used a bot for Telegram, their policy is somewhat more open than Whatsapp I think. 

But can you succesfully implement ZermeloRoosterPHP into your bot?

**Comment by BasvdW22** [comment]
Yea, I know Telegram, but nobody I know uses it :P. 
And I haven't tried implementing it in the bot yet, still don't have the new sim card for it.

**Comment by wvanbreukelen** [comment]
That bad, let's hope it wil arrive soon.

By the way, I manage to fix the issue you addressed with the cache.json file creation.
So if you re-clone the code in the future, you will not have to create the file manually

**Comment by BasvdW22** [comment]
Ah okay, good to know, thanks :).
