### ISSUE TITLE
Using outside root directory (FIXED)

### ISSUE THREAD

**Issue by basvdwollenberg** [wvanbreukelen/ZermeloRoosterPHP#12]
This isn't working or I'm just stupid lol.
I have ZermeloRoosterPHP in a subdirectory (submodule) of my project and the actual script in the root directory, but that isn't really working. I tried changing custom_autoload.php to my needs, but because Cache.php (didn't check Zermelo.php) is checking for the directory (and I don't want to change everything manually) this also won't work. Do you know a solution or should I just use a remote?

**Comment by wvanbreukelen** [comment]
Ok, please send me the file structure,you can do that with a linux command, something like ls. Unfortally, the ls command does not list subdirectories, so please search for a command that can do that.

If you send me the structure, I can create a custom autoloader for you and explain the changes.

**Comment by BasvdW22** [comment]
ls -lR
![](https://i.imgur.com/XknvnNf.png)

**Comment by wvanbreukelen** [comment]
At first, sorry for the late answer.

I suppose that the first directory (.) is the directory that your script has to go in.
I think that you just could include the custom_autoloader.php file in your script like this.

```php
require('ZermeloRoosterPHP/custom_autoload.php');
```

You have to add that directly under the <?php tag.

Like this
```php
<?php

require('ZermeloRoosterPHP/custom_autoload.php');

// The rest for your own script file
```

**Comment by BasvdW22** [comment]
I think have tried that already, can't try it again because the SD card for my Raspberry Pi just got corrupted, restoring an old back-up and have to reconfigure & reinstall everything. Will try it again after I've set everything up.

**Comment by wvanbreukelen** [comment]
Oh, thats too bad. Actually, my Pi 2 got corrupted today when I tried to resize the os partition because it was too small ;)

I am going to sleep now, so maybe tomorrow I can improvise a new autoloader.

**Comment by wvanbreukelen** [comment]
Ok, try the following

```php
<?php

$rootDir = 'ZermeloRoosterPHP/';

function register_zermelo_api()
{
	if (file_exists($rootDir . 'Cache.php'))
	{
		include_once($rootDir . 'Cache.php');
	} else {
		throw new Exception("$rootDirCache.php has not been found!");
	}
	
	if (file_exists($rootDir . 'Zermelo.php'))
	{
		include_once($rootDir . 'Zermelo.php');
	} else {
		throw new Exception("$rootDirZermelo.php has not been found!");
	}	
}
```

**Comment by BasvdW22** [comment]
I moved '''php $rootDir = 'ZermeloRoosterPHP/';''' inside the function, otherwise I would get '''PHP Notice:  Undefined variable: rootDir in /home/pi/V3A-Telegram-Bot-PHP/ZermeloRoosterPHP/custom_autoload.php on line 7
PHP Notice:  Undefined variable: rootDir in /home/pi/V3A-Telegram-Bot-PHP/ZermeloRoosterPHP/custom_autoload.php on line 9
PHP Notice:  Undefined variable: rootDir in /home/pi/V3A-Telegram-Bot-PHP/ZermeloRoosterPHP/custom_autoload.php on line 14
PHP Notice:  Undefined variable: rootDir in /home/pi/V3A-Telegram-Bot-PHP/ZermeloRoosterPHP/custom_autoload.php on line 16''' everytime I (re)started the bot.
Anyway, thanks!

**Comment by BasvdW22** [comment]
Oh well, it still didn't work lol.  accidentally tried it with all the ZermeloRoosterPHP files still in the project, still can't find Cache.php

**Comment by wvanbreukelen** [comment]
That's weird.

Ok, I will do some more debugging. 
Please change all the code in the custom_autoloader.php file to the following:

```php
<?php

function register_zermelo_api()
{
    $rootDir = 'ZermeloRoosterPHP/';

    echo "Expected Cache Dir: " . $rootDir . 'Cache.php';

    if (file_exists($rootDir . 'Cache.php'))
    {
        echo "Cache OK!"
        include_once($rootDir . 'Cache.php');
    } else {
        echo "Cache FAIL!";
        //throw new Exception("$rootDirCache.php has not been found!");
    }

    echo "Expected Zermelo Dir: " . $rootDir . 'Zermelo.php';

    if (file_exists($rootDir . 'Zermelo.php'))
    {
        echo "Zermelo OK!"
        include_once($rootDir . 'Zermelo.php');
    } else {
        echo "Cache FAIL!";
        //throw new Exception("$rootDirZermelo.php has not been found!");
    }   
}
```

**Comment by BasvdW22** [comment]
Oh well, it does work, but only if I have the cache.json file in the project directory and that's not really a problem, so I guess this is solved now :).

**Comment by wvanbreukelen** [comment]
Haha lolol. Yeah I did some quick coding, because I had dinner downstairs.

But it is great to hear that your issue has been fixed.
I will keep this one open so you can ask other things, if you like.

**Comment by BasvdW22** [comment]
Alright, when I know something to ask I'll do ;).

**Comment by BasvdW22** [comment]
This is not really a programming related question, but could you try out @ZermeloBot on Telegram? I extended the V3A Telegram Bot so more schools can use it. (I'll clean my code later, it's extremely messy right now lol.)

**Comment by wvanbreukelen** [comment]
I will try that!

**Comment by wvanbreukelen** [comment]
I tried your bot, it seems to be functioning great! Only my personal grid can not be accessed I think because I am on a different school. Do you have the code available on github, so I can clone it and try it out?
It would be great!

**Comment by BasvdW22** [comment]
The bot wasn't functioning like it should an hour ago, I was still working on some new things (with the custom keyboard). I'll push some new code with the custom keyboard soon.
And I just saw your rewrite, I still have to learn a lot :P.

**Comment by wvanbreukelen** [comment]
EDIT response: Have a look here: http://www.phphulp.nl/php/tutorial/overig/oop-beginnershandleiding-php5/701/

EDIT 2 response: Oh, I can have a look at this tomorrow.

**Comment by BasvdW22** [comment]
I'll take a look at that tomorrow.

**Comment by wvanbreukelen** [comment]
This issue keeps open for possible conversations with @BasvdW22

**Comment by basvdwollenberg** [comment]
Don't think we need this anymore :P.
