### ISSUE TITLE
example.php outdated

### ISSUE THREAD

**Issue by quinten1333** [wvanbreukelen/ZermeloRoosterPHP#18]
in your example.php you have a line 
`// Get a new access token using a username and code
$zermelo->grabAccessToken('user', 'code');` 
but code can refer to the link app code or your password, so i've been using the wrong code to get in.

on the question what i'm making:
i'm making an php handle for my first app (c#)

**Comment by wvanbreukelen** [comment]
You may want to use the 1.0.6 stable release instead of the master branch. This one is well tested for errors.
